linters:
  LineLength:
    max: 100

  RuboCop:
    enabled: true
    ignored_cops:
      # These cops are incredibly noisy since the Ruby we extract from Slim
      # templates isn't well-formatted, so we ignore them.
      - Layout/AlignArguments
      - Layout/AlignArray
      - Layout/AlignHash
      - Layout/AlignParameters
      - Layout/EmptyLineAfterGuardClause
      - Layout/FirstParameterIndentation
      - Layout/IndentArray
      - Layout/IndentationConsistency
      - Layout/IndentationWidth
      - Layout/InitialIndentation
      - Layout/MultilineArrayBraceLayout
      - Layout/MultilineAssignmentLayout
      - Layout/MultilineHashBraceLayout
      - Layout/MultilineMethodCallBraceLayout
      - Layout/MultilineMethodCallIndentation
      - Layout/MultilineMethodDefinitionBraceLayout
      - Layout/MultilineOperationIndentation
      - Layout/TrailingBlankLines
      - Layout/TrailingWhitespace
      - Lint/BlockAlignment
      - Lint/EndAlignment
      - Lint/Void
      - Metrics/BlockLength
      - Metrics/BlockNesting
      - Metrics/LineLength
      - Naming/FileName
      - Style/FrozenStringLiteralComment
      - Style/IfUnlessModifier
      - Style/Next
      - Style/WhileUntilModifier
      # Also ignoring this cop since it is redundantly checked by brakeman
      - Rails/OutputSafety
