services:
  db:
    image: postgres:11-bullseye
    container_name: wri_db
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  rails:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - bundle_cache:/bundle
    ports:
      - "3010:3010"
    environment:
      - RAILS_ENV=development
      - PORT=3010
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
    command: bundle exec rails s -b 0.0.0.0
    tty: true
    stdin_open: true
    depends_on:
      - db

  # chrome:
  #   image: browserless/chrome:1-puppeteer-15.5.0-slim
  #   ports:
  #     - "3333:3333"
  #   # Mount application source code to support file uploading
  #   # (otherwise Chrome won't be able to find files).
  #   # NOTE: Make sure you use absolute paths in `#attach_file`.
  #   environment:
  #     # By default, it uses 3000, which is typically used by Rails.
  #     PORT: 3333
  #     # Set connection timeout to avoid timeout exception during debugging
  #     # https://docs.browserless.io/docs/docker.html#connection-timeout
  #     CONNECTION_TIMEOUT: 600000

volumes:
  bundle_cache:
  dbdata: