version: "3.8"
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/vhost.d:/etc/nginx/vhost.d:ro
    restart: unless-stopped
networks:
  default:
    external:
      name: nginx-proxy
