class UpdateWidgetDatapointColumnsMar2022 < ActiveRecord::Migration[5.2]
  def change
    # rename_column :widget_datapoints, "month_date", "month_date"
    # rename_column :widget_datapoints, "GID_2", "GID_2"
    # rename_column :widget_datapoints, "GID_1", "GID_1"
    # rename_column :widget_datapoints, "GID_0", "GID_0"
    # rename_column :widget_datapoints, "year_date", "year_date"
    # rename_column :widget_datapoints, "year", "year"
    # rename_column :widget_datapoints, "month", "month"
    # rename_column :widget_datapoints, "acl_sum_fatl", "acl_sum_fatl"
    # rename_column :widget_datapoints, "ndvi_act_avg", "ndvi_act_avg"
    # rename_column :widget_datapoints, "spi_24", "spi_24"
    # rename_column :widget_datapoints, "spi_3_f2", "spi_3_f2"
    # rename_column :widget_datapoints, "swe_area", "swe_area"
    # rename_column :widget_datapoints, "energy_all", "energy_all"
    # rename_column :widget_datapoints, "food_all", "food_all"
    # rename_column :widget_datapoints, "water_all", "water_all"
    # rename_column :widget_datapoints, "bws", "bws"
    # rename_column :widget_datapoints, "iav", "iav"
    # rename_column :widget_datapoints, "rfr", "rfr"
    # rename_column :widget_datapoints, "sev", "sev"
    # rename_column :widget_datapoints, "wspowerprd", "wspowerprd"
    # rename_column :widget_datapoints, "buffalo_number", "buffalo_number"
    # rename_column :widget_datapoints, "cattle_number", "cattle_number"
    # rename_column :widget_datapoints, "chicken_number", "chicken_number"
    # rename_column :widget_datapoints, "Cropland2000_mean_percent", "Cropland2000_mean_percent"
    # rename_column :widget_datapoints, "DeliveredkcalFraction", "DeliveredkcalFraction"
    # rename_column :widget_datapoints, "duck_number", "duck_number"
    # rename_column :widget_datapoints, "goat_number", "goat_number"
    # rename_column :widget_datapoints, "horse_number", "horse_number"
    # rename_column :widget_datapoints, "Pasture2000_mean_percent", "Pasture2000_mean_percent"
    # rename_column :widget_datapoints, "pig_number", "pig_number"
    # rename_column :widget_datapoints, "rainfed", "rainfed"
    # rename_column :widget_datapoints, "sheep_number", "sheep_number"
    # rename_column :widget_datapoints, "spam_P_i_ws", "spam_P_i_ws"
    # rename_column :widget_datapoints, "spam_P_r_sum", "spam_P_r_sum"
    # rename_column :widget_datapoints, "spam_V_agg_i_sum", "spam_V_agg_i_sum"
    # rename_column :widget_datapoints, "spam_V_agg_r_sum", "spam_V_agg_r_sum"
    # rename_column :widget_datapoints, "spam_V_agg_t_sum", "spam_V_agg_t_sum"
    # rename_column :widget_datapoints, "yield_gap_barley", "yield_gap_barley"
    # rename_column :widget_datapoints, "yield_gap_maize", "yield_gap_maize"
    # rename_column :widget_datapoints, "yield_gap_rice", "yield_gap_rice"
    # rename_column :widget_datapoints, "yield_gap_soybean", "yield_gap_soybean"
    rename_column :widget_datapoints, "age_65+", "age_65"
    # rename_column :widget_datapoints, "al_ethnic", "al_ethnic"
    # rename_column :widget_datapoints, "al_religion", "al_religion"
    # rename_column :widget_datapoints, "bci_bci", "bci_bci"
    rename_column :widget_datapoints, "EG.ELC.ACCS.ZS", "EG-ELC-ACCS-ZS"
    rename_column :widget_datapoints, "EG.ELC.LOSS.ZS", "EG-ELC-LOSS-ZS"
    rename_column :widget_datapoints, "EG.IMP.CONS.ZS", "EG-IMP-CONS-ZS"
    # rename_column :widget_datapoints, "elec_expt_totl", "elec_expt_totl"
    # rename_column :widget_datapoints, "elec_impt_totl", "elec_impt_totl"
    # rename_column :widget_datapoints, "elect_dist_loss", "elect_dist_loss"
    # rename_column :widget_datapoints, "eng_cons_pcap", "eng_cons_pcap"
    # rename_column :widget_datapoints, "eng_cons_pgdp", "eng_cons_pgdp"
    # rename_column :widget_datapoints, "eng_cons_totl", "eng_cons_totl"
    # rename_column :widget_datapoints, "eng_prod_totl", "eng_prod_totl"
    rename_column :widget_datapoints, "EP.PMP.DESL.CD", "EP-PMP-DESL-CD"
    # rename_column :widget_datapoints, "fd_ex_per", "fd_ex_per"
    # rename_column :widget_datapoints, "fd_im_per", "fd_im_per"
    rename_column :widget_datapoints, "FP.CPI.TOTL.ZG", "FP-CPI-TOTL-ZG"
    rename_column :widget_datapoints, "IC.FRM.OUTG.ZS", "IC-FRM-OUTG-ZS"
    rename_column :widget_datapoints, "NV.AGR.TOTL.ZS", "NV-AGR-TOTL-ZS"
    rename_column :widget_datapoints, "NY.GDP.PCAP.PP.KD", "NY-GDP-PCAP-PP-KD"
    # rename_column :widget_datapoints, "sanitationaccess", "sanitationaccess"
    # rename_column :widget_datapoints, "sex_25-64", "sex_25-64"
    rename_column :widget_datapoints, "sex_65+", "sex_65"
    rename_column :widget_datapoints, "SH.STA.STNT.ZS", "SH-STA-STNT-ZS"
    rename_column :widget_datapoints, "SI.POV.LMIC", "SI-POV-LMIC"
    rename_column :widget_datapoints, "SL.AGR.EMPL.ZS", "SL-AGR-EMPL-ZS"
    rename_column :widget_datapoints, "SL.UEM.TOTL.ZS", "SL-UEM-TOTL-ZS"
    rename_column :widget_datapoints, "SP.DYN.IMRT.IN", "SP-DYN-IMRT-IN"
    # rename_column :widget_datapoints, "wateraccess", "wateraccess"
    # rename_column :widget_datapoints, "urbrate", "urbrate"
    # rename_column :widget_datapoints, "loss_ha", "loss_ha"
    # rename_column :widget_datapoints, "et_anom_y_MIN", "et_anom_y_MIN"
    # rename_column :widget_datapoints, "locdensity", "locdensity"
    # rename_column :widget_datapoints, "conflict_cat", "conflict_cat"
  end
end
