name: Update 24-month SPI Anomaly (Long-term)

on:
  workflow_dispatch:
    # Allows manual triggering of the action
  schedule:
    - cron: "0 12 * * *" # Runs daily at 12:00 UTC, adjust as needed

jobs:
  spi-24-month:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Upgrade pip & Install dependencies
        run: |
          pip -U pip==22.0 --force
          echo "Installing Python dependencies"
          if [ -f ./python/requirements.txt ]; then pip install -r ./python/requirements.txt; fi
          pip install rasterio
          pip install earthengine-api
          pip install earthengine-api --upgrade

      # - name: "auth"
      #   uses: "google-github-actions/auth@v2"
      #   with:
      #     workload_identity_provider: "projects/297470958436/locations/global/workloadIdentityPools/wps-github-action-automations/providers/wps-github"
      #     service_account: "wps-automation@wpsi-208318.iam.gserviceaccount.com"

      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      # Get file source name and put it on env
      - name: Run Python Script on File
        run: |
          python python/getFilename24month.py

      - name: Copy from Google storage to local
        run: |
          gcloud storage cp $WPS_24_MONTH_GS $WPS_24_MONTH_FILENAME.tif

      # Get file source name and put it on env
      - name: Project downloaded file
        run: |
          python python/project.py

      # - name: Copy to Google storage to
      #   run: |
      #     gcloud storage cp $WPS_24_MONTH_FILENAME.tif $WPS_24_MONTH_GS_PROJ

      # - name: Running earth engine script
      #   run: |
      #     ls -la
      #     SA_FILE=$(ls gha-creds-* | head -n 1)
      #     earthengine --service_account_file $SA_FILE upload image --asset_id=projects/wpsi-208318/assets/wpsi/$WPS_24_MONTH_FILENAME $WPS_24_MONTH_GS_PROJ --force

      # - name: "Use earthengine"
      #   run: "earthengine upload image --asset_id=projects/wpsi-208318/assets/testaction $WPS_24_MONTH_GS_PROJ"
